### ISSUE TITLE
Module conflict with sha3 on python 2.7

### ISSUE THREAD

**Issue by kompjoefriek** [tiran/pysha3#12]
This is the same issue as #8 which was declared invalid, probably because it was missing crucial information on how to reproduce it. This user on StackOverflow managed to stumble upon it: https://stackoverflow.com/questions/46279121/how-can-i-find-keccak-256-hash-in-python

On Python 2.7:
install both sha3 and pysha3 via pip:
`python -m pip install sha3 pysha3`

Then try the example code:
```python
import sha3
k = sha3.keccak_512()
k.update("data")
k.hexdigest()
```

This seems to import the sha3 module from the sha3 package, not the pysha3 package.

**Comment by tiran** [comment]
There is not much I can do about this. The packages have have colliding module names.

**Comment by priyanshgupta1998** [comment]
yes , i got same problem when i was trying to import sha3 in python 3.x.
that >>> "No module name "sha3"
then i installed this package by using this following command
>>> python -m pip install sha3
i had to face again same error. then i uninstalled it and instead of this (sha3) i installed 'pysha3' package.
now it's work perfectly fine.
>>> python -m pip install pysha3

**Comment by tiran** [comment]
pysha3 is no longer supported. Please use SHA-3 from Python's hashlib module.
